all:
	gcc -Wall -g main.c arrCard/arrCard.c arrKota/arrKota.c \
		listOffered/listOffered.c listBoard/listBoard.c listPlayer/listPlayer.c \
		listSabotage/listSabotage.c str/mesinkata.c str/mesinkar.c str/str.c -o main

nowarn:
	gcc -Wall -g main.c arrCard/arrCard.c arrKota/arrKota.c \
		listOffered/listOffered.c listBoard/listBoard.c listPlayer/listPlayer.c \
		listSabotage/listSabotage.c str/mesinkata.c str/mesinkar.c str/str.c -o main
